#!/usr/bin/env python3
"""Copy game assets (source, binary, walkthrough) from projects into hub games/.

Reads deploy fields from games.json to find source paths. Replaces the
hardcoded GAMES[] and WALKTHROUGH_DIRS[] bash arrays in deploy.sh.

Usage:
    python3 copy-assets.py --games-json PATH --i7-root PATH [--output-dir PATH]
"""

import argparse
import json
import os
import shutil


WALKTHROUGH_FILES = [
    # walkthrough.html is now generated by generate-walkthrough-pages.py
    "walkthrough.txt",
    "walkthrough-guide.txt",
    "walkthrough_output.txt",
]


def main():
    parser = argparse.ArgumentParser(description="Copy game assets from projects")
    parser.add_argument("--games-json", required=True, help="Path to games.json")
    parser.add_argument("--i7-root", required=True, help="ifhub root directory")
    parser.add_argument("--output-dir", default="games", help="Base output directory")
    args = parser.parse_args()

    with open(args.games_json, encoding="utf-8") as f:
        games = json.load(f)

    for g in games:
        gid = g["id"]
        deploy = g.get("deploy")
        if not deploy:
            print(f"  {gid}: WARNING — no deploy config, skipping")
            continue

        dest = os.path.join(args.output_dir, gid)
        os.makedirs(dest, exist_ok=True)

        # Copy source (.ni)
        src = deploy.get("source")
        if src:
            src_path = os.path.join(args.i7_root, src)
            if os.path.isfile(src_path):
                shutil.copy2(src_path, os.path.join(dest, "story.ni"))
                print(f"  {gid}: story.ni copied")
            else:
                print(f"  {gid}: WARNING — {src} not found, skipping source")

        # Copy binary
        binary = deploy.get("binary")
        if binary:
            bin_path = os.path.join(args.i7_root, binary)
            if os.path.isfile(bin_path):
                shutil.copy2(bin_path, os.path.join(dest, os.path.basename(binary)))
                print(f"  {gid}: {os.path.basename(binary)} copied")
            else:
                print(f"  {gid}: WARNING — {binary} not found, skipping binary")

        # Copy walkthrough files
        wt_dir = deploy.get("walkthroughDir")
        if wt_dir:
            wt_path = os.path.join(args.i7_root, wt_dir)
            # Derive base project name (e.g. "zork1-v4" → "zork1", "sample" → "sample")
            base_id = gid.split("-")[0]
            for wf in WALKTHROUGH_FILES:
                wf_src = os.path.join(wt_path, wf)
                if os.path.isfile(wf_src):
                    shutil.copy2(wf_src, os.path.join(dest, wf))
                    print(f"  {gid}: {wf} copied")
                else:
                    # Fallback: search project's tests/ and tests/inform7/ directories
                    found = False
                    for trydir in [
                        f"projects/{base_id}/tests",
                        f"projects/{base_id}/tests/inform7",
                    ]:
                        trypath = os.path.join(args.i7_root, trydir, wf)
                        if os.path.isfile(trypath):
                            shutil.copy2(trypath, os.path.join(dest, wf))
                            print(f"  {gid}: {wf} copied (from {trydir})")
                            found = True
                            break
                    if not found:
                        print(f"  {gid}: WARNING — {wf} not found in {wt_dir}")


if __name__ == "__main__":
    main()
