#!/usr/bin/env python3
"""Render combined landing pages for versioned-game groups.

Reads:
    - games-registry.json (group membership, paths)
    - site/games.json      (titles, play URLs)
    - <group-path>/landing.json  (per-group prose: intro, per-version blurbs)
    - tools/web/templates/versioned-landing.html.tmpl

Writes:
    - <group-path>/index.html         (separate-repo groups, e.g., zork1)
    - <group-path>/browser/index.html (shared-repo groups with `subpath`, e.g., familyzoo)

Safety: refuses to overwrite a landing file that lacks the
`generated by build_landing.py` marker on its first line, unless --force.

Usage:
    python tools/build_landing.py --all
    python tools/build_landing.py zork1
    python tools/build_landing.py zork1 familyzoo --force
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.paths import IFHUB_DIR, GAMES_REGISTRY, TOOLS_DIR, I7_ROOT
import build_games


TEMPLATE_PATH = TOOLS_DIR / "web" / "templates" / "versioned-landing.html.tmpl"
MARKER = "<!-- generated by build_landing.py -->"


def resolve_path(raw: str) -> Path:
    p = Path(raw)
    if not p.is_absolute():
        p = (I7_ROOT / p).resolve()
    return p


def render_version_nav(primary_id: str, members_ordered: list[tuple[str, dict, dict]]) -> str:
    """Small top-of-page nav bar with chips for each version + a 'Current' chip.

    Non-primary chips link to the in-page anchor (#<gid>) for that version's
    blurb on this same landing page.
    """
    parts = []
    for gid, entry, game in members_ordered:
        label = entry.get("_label", game.get("title", gid))
        if gid == primary_id:
            parts.append(f'<span class="current">{label}</span>')
        else:
            parts.append(f'<a href="#{gid}">{label}</a>')
    return "\n  ".join(parts)


def render_version_entries(primary_id: str,
                           members_ordered: list[tuple[str, dict, dict]],
                           landing_versions: dict) -> str:
    """Detailed per-version cards: summary + feature list + action dropdown.

    Mirrors the IF Hub card UI: a 'View'/'Play' action dropdown, a Fullscreen
    checkbox, and a GO button. Click handling is wired by the template's
    delegated script using data-* attributes on each block.
    """
    blocks = []
    for gid, entry, game in members_ordered:
        label = entry.get("_label", game.get("title", gid))
        primary_class = " primary" if gid == primary_id else ""
        blurb = landing_versions.get(gid, {})
        summary = blurb.get("summary", "")
        features = blurb.get("features", [])

        features_html = ""
        if features:
            lis = "\n    ".join(f"<li>{f}</li>" for f in features)
            features_html = f'\n  <ul>\n    {lis}\n  </ul>'

        play_url = game.get("playUrl", f"/{gid}/play.html")
        source_url = game.get("sourceUrl", "")
        walkthrough_url = game.get("walkthroughUrl", "")

        action_opts = ['<option value="play">Play Game</option>']
        if source_url:
            action_opts.append('<option value="source">View Source</option>')
        if walkthrough_url:
            action_opts.append('<option value="walkthrough">View Walkthrough</option>')

        controls_html = (
            f'  <div class="version-action"'
            f' data-gid="{gid}"'
            f' data-play="{play_url}"'
            f' data-source="{source_url}"'
            f' data-walkthrough="{walkthrough_url}">\n'
            f'    <select class="va-action">{"".join(action_opts)}</select>\n'
            f'    <label class="va-fs"><input type="checkbox"> Fullscreen</label>\n'
            f'    <button class="va-go" type="button">GO</button>\n'
            f'  </div>'
        )

        summary_html = f"<p>{summary}</p>" if summary else ""

        blocks.append(
            f'<div class="version-entry{primary_class}" id="{gid}">\n'
            f'  <h3>{label}</h3>\n'
            f'  {summary_html}{features_html}\n'
            f'{controls_html}\n'
            f'</div>'
        )
    return "\n\n".join(blocks)


def landing_target(primary_entry: dict, primary_path: Path) -> Path:
    """Where to write the group landing file.

    Shared-repo groups (primary has `subpath`) → <path>/browser/index.html.
    Separate-repo groups → <path>/index.html.
    """
    if primary_entry.get("subpath"):
        return primary_path / "browser" / "index.html"
    return primary_path / "index.html"


def check_marker_or_abort(target: Path, force: bool) -> bool:
    """Return True if safe to write. False (with message) if not."""
    if not target.exists() or force:
        return True
    first_line = target.read_text(encoding="utf-8").splitlines()[0] if target.read_text(encoding="utf-8") else ""
    if MARKER in first_line:
        return True
    print(f"  skip: {target} is hand-written (no marker). Use --force to overwrite.")
    return False


def build_for_group(base: str,
                    primary_meta: dict,
                    member_to_base: dict,
                    games_by_id: dict,
                    registry: dict,
                    template: str,
                    force: bool) -> None:
    primary_id = primary_meta["primary_id"]
    primary_entry = registry.get(primary_id, {})
    primary_game = games_by_id.get(primary_id)
    if not primary_game:
        print(f"  warn: primary '{primary_id}' not in games.json, skipping")
        return

    primary_path = resolve_path(primary_entry.get("path", ""))
    if primary_path == Path() or not primary_path.exists():
        print(f"  warn: primary path {primary_path} does not exist, skipping '{base}'")
        return

    target = landing_target(primary_entry, primary_path)
    if not check_marker_or_abort(target, force):
        return

    # Load optional per-group landing.json from the game's own repo.
    landing_json_path = primary_path / "landing.json"
    landing: dict = {}
    if landing_json_path.exists():
        try:
            landing = json.loads(landing_json_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            print(f"  warn: could not parse {landing_json_path}: {e}")

    landing_versions = landing.get("versions", {})

    # Order members primary-first, then by versionOrder desc.
    all_members = [gid for gid, b in member_to_base.items() if b == base]
    non_primary = [m for m in all_members if m != primary_id]
    non_primary.sort(
        key=lambda g: build_games.version_order(g, registry.get(g, {})),
        reverse=True,
    )
    ordered_ids = [primary_id] + non_primary

    members_ordered = []
    for gid in ordered_ids:
        entry = dict(registry.get(gid, {}))
        game = games_by_id.get(gid, {})
        entry["_label"] = build_games.version_label(gid, entry, game) \
            if gid != primary_id else \
            (primary_meta["primary_label"])
        members_ordered.append((gid, entry, game))

    title = landing.get("title") or primary_game.get("title", primary_id)
    subtitle = landing.get("subtitle", "")
    meta = landing.get("meta", "")
    description = landing.get("description") or primary_game.get("title", "")
    intro_html = landing.get("introHtml", "")
    outro_html = landing.get("outroHtml", "")
    primary_cta_label = landing.get("primaryCtaLabel", "Play")

    rendered = (template
                .replace("{{TITLE}}", title)
                .replace("{{SUBTITLE}}", subtitle)
                .replace("{{META}}", meta)
                .replace("{{DESCRIPTION}}", description)
                .replace("{{INTRO_HTML}}", intro_html)
                .replace("{{OUTRO_HTML}}", outro_html)
                .replace("{{PRIMARY_PLAY_URL}}", primary_game.get("playUrl", f"/{primary_id}/play.html"))
                .replace("{{PRIMARY_CTA_LABEL}}", primary_cta_label)
                .replace("{{PRIMARY_ID}}", primary_id)
                .replace("{{VERSION_NAV}}", render_version_nav(primary_id, members_ordered))
                .replace("{{VERSION_ENTRIES}}", render_version_entries(primary_id, members_ordered, landing_versions))
                )

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    print(f"  wrote {target}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Render combined landing pages for versioned groups.")
    parser.add_argument("bases", nargs="*", help="Base ids to build (e.g., zork1 familyzoo)")
    parser.add_argument("--all", action="store_true", help="Build landings for all versioned groups")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite files without the generator marker")
    args = parser.parse_args()

    if not args.all and not args.bases:
        parser.error("pass --all or one or more base ids")

    games = json.loads((IFHUB_DIR / "games.json").read_text(encoding="utf-8"))
    registry = json.loads(GAMES_REGISTRY.read_text(encoding="utf-8"))
    template = TEMPLATE_PATH.read_text(encoding="utf-8")

    games_by_id = {g["id"]: g for g in games}
    member_to_base, primaries = build_games.build_groups(registry)

    if args.all:
        targets = list(primaries.keys())
    else:
        targets = args.bases
        for b in targets:
            if b not in primaries:
                print(f"  error: no primary found for base '{b}' — "
                      "add versionPrimary: true to a registry entry")
                sys.exit(1)

    for base in targets:
        print(f"[{base}]")
        build_for_group(base, primaries[base], member_to_base,
                        games_by_id, registry, template, args.force)


if __name__ == "__main__":
    main()
