#!/bin/bash
# Create a new Inform 7 project with build, test, and web infrastructure.
#
# Usage:
#   bash /c/code/ifhub/tools/new-project.sh "Game Title" game-name
#
# Example:
#   bash /c/code/ifhub/tools/new-project.sh "The Haunted Manor" manor
#
# Creates:
#   C:\code\ifhub\projects\<game-name>\
#   ├── story.ni                    Starter source
#   ├── CLAUDE.md                   Project guide
#   ├── .gitignore
#   ├── .github/workflows/deploy-pages.yml
#   ├── tests/
#   │   ├── project.conf            Test configuration
#   │   ├── run-tests.sh            RegTest wrapper
#   │   ├── run-walkthrough.sh      Walkthrough wrapper
#   │   ├── find-seeds.sh           Seed sweeper wrapper
#   │   ├── seeds.conf              Golden seeds (TBD)
#   │   ├── <name>.regtest          Starter regression test
#   │   └── inform7/
#   │       └── walkthrough.txt     Starter walkthrough
#   └── web/                        (created later by compile-and-deploy)
#
# After creation:
#   1. Edit story.ni to build your game
#   2. Compile:  bash /c/code/ifhub/tools/compile.sh <game-name>
#   3. Test:     wsl -e bash tests/run-tests.sh
#   4. Publish:  bash /c/code/ifhub/tools/publish.sh <game-name>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
I7_ROOT="$(dirname "$SCRIPT_DIR")"

# --- Args ---
if [[ $# -lt 2 ]]; then
    echo "Usage: $0 \"Game Title\" game-name" >&2
    echo "  Example: $0 \"The Haunted Manor\" manor" >&2
    exit 1
fi

TITLE="$1"
NAME="$2"
PROJECT_DIR="$I7_ROOT/projects/$NAME"

if [[ -d "$PROJECT_DIR" ]]; then
    echo "ERROR: Directory already exists: $PROJECT_DIR" >&2
    exit 1
fi

echo "Creating project: $TITLE ($NAME)"
echo "  Location: $PROJECT_DIR"
echo ""

# --- Directories ---
mkdir -p "$PROJECT_DIR/tests/inform7"
mkdir -p "$PROJECT_DIR/.github/workflows"

# --- story.ni ---
cat > "$PROJECT_DIR/story.ni" << STORY_EOF
"$TITLE" by "Johnesco"

The story headline is "An Interactive Fiction".
The story genre is "Fantasy".
The release number is 1.
The story creation year is $(date +%Y).
The story description is "An interactive fiction game."

Use American dialect.
Use scoring.
The maximum score is 1.

Part 1 - Configuration

When play begins:
	now the left hand status line is "[the player's surroundings]   Score: [score]/[turn count]";
	now the right hand status line is "";
	say "[bold type]$TITLE[roman type][line break]An Interactive Fiction by Johnesco[paragraph break]".

Part 2 - The World

The Starting Room is a room. "You are in an empty room. This is where your game begins."
STORY_EOF

# --- .gitignore ---
cat > "$PROJECT_DIR/.gitignore" << 'GITIGNORE_EOF'
# Assembled site output (generated by build-site.sh / CI)
_site/

# Build output
*.ulx
*.i6
*.materials/

# Inform 7 IDE project wrappers
*.inform/

# Claude Code local settings
.claude/

# Test output (generated)
tests/inform7/walkthrough_output.txt

# OS generated files
$RECYCLE.BIN/
[Dd]esktop.ini
.DS_Store
Thumbs.db
*~
.*.sw[op]

# IDE
.vscode/
.idea/
GITIGNORE_EOF

# --- deploy-pages.yml ---
cat > "$PROJECT_DIR/.github/workflows/deploy-pages.yml" << 'WORKFLOW_EOF'
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - name: Assemble site
        run: |
          mkdir -p _site
          cp -r web/* _site/
          if [ -d versions ]; then
            for v in versions/*/; do
              cp -r "$v" "_site/$(basename "$v")"
            done
          fi
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - id: deployment
        uses: actions/deploy-pages@v4
WORKFLOW_EOF

# --- tests/project.conf ---
cat > "$PROJECT_DIR/tests/project.conf" << CONF_EOF
#!/bin/bash
# $TITLE — project-specific test configuration
# Sourced by the generic testing framework (tools/testing/*.sh)
#
# PROJECT_DIR is set by the framework before sourcing this file.

# Project identity
PROJECT_NAME="$TITLE"

# Primary engine (Inform 7 / Glulx)
PRIMARY_ENGINE_NAME="glulxe"
PRIMARY_ENGINE_PATH="\$HOME/glulxe/glulxe"
PRIMARY_ENGINE_SEED_FLAG="--rngseed"
PRIMARY_GAME_PATH="\$PROJECT_DIR/$NAME.ulx"
PRIMARY_WALKTHROUGH="\$PROJECT_DIR/tests/inform7/walkthrough.txt"
PRIMARY_OUTPUT_FILE="\$PROJECT_DIR/tests/inform7/walkthrough_output.txt"
PRIMARY_SEEDS_KEY="glulxe"

# Score extraction patterns (Inform 7 default output format)
SCORE_REGEX='scored \K[0-9]+'
SCORE_FALLBACK_REGEX='[0-9]+(?= out of a possible [0-9]+)'
MAX_SCORE_REGEX='possible \K[0-9]+'
PASS_THRESHOLD=1
DEFAULT_MAX_SCORE=1

# Diagnostic patterns
DEATH_PATTERNS='you have died'
WON_PATTERNS='You have won'

# RegTest config
REGTEST_FILE="\$PROJECT_DIR/tests/$NAME.regtest"
REGTEST_ENGINE="\$HOME/glulxe/glulxe"
REGTEST_GAME="\$PROJECT_DIR/$NAME.ulx"
CONF_EOF

# --- Test wrapper scripts ---
cat > "$PROJECT_DIR/tests/run-tests.sh" << 'WRAPPER_EOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
I7_HUB="/mnt/c/code/ifhub"
CONFIG="$SCRIPT_DIR/project.conf"
exec bash "$I7_HUB/tools/testing/run-tests.sh" --config "$CONFIG" "$@"
WRAPPER_EOF

cat > "$PROJECT_DIR/tests/run-walkthrough.sh" << 'WRAPPER_EOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
I7_HUB="/mnt/c/code/ifhub"
CONFIG="$SCRIPT_DIR/project.conf"
exec bash "$I7_HUB/tools/testing/run-walkthrough.sh" --config "$CONFIG" "$@"
WRAPPER_EOF

cat > "$PROJECT_DIR/tests/find-seeds.sh" << 'WRAPPER_EOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
I7_HUB="/mnt/c/code/ifhub"
CONFIG="$SCRIPT_DIR/project.conf"
exec bash "$I7_HUB/tools/testing/find-seeds.sh" --config "$CONFIG" "$@"
WRAPPER_EOF

# --- seeds.conf ---
cat > "$PROJECT_DIR/tests/seeds.conf" << 'SEEDS_EOF'
# Golden seeds for deterministic walkthrough testing
# Format: engine:seed:binary_hash:date
# Re-discover with: bash tests/find-seeds.sh
#
# glulxe:TBD:TBD:TBD
SEEDS_EOF

# --- Starter regtest ---
cat > "$PROJECT_DIR/tests/$NAME.regtest" << REGTEST_EOF
** game: ../$NAME.ulx
** interpreter: /home/johnesco/glulxe/glulxe -q

* smoke
> look
Starting Room
REGTEST_EOF

# --- Starter walkthrough ---
cat > "$PROJECT_DIR/tests/inform7/walkthrough.txt" << 'WALK_EOF'
look
WALK_EOF

# --- CLAUDE.md ---
cat > "$PROJECT_DIR/CLAUDE.md" << CLAUDE_EOF
# $TITLE — An Inform 7 Game

## Project Structure

\`\`\`
C:\\code\\ifhub\\projects\\$NAME\\
├── CLAUDE.md              ← You are here
├── story.ni               ← Source of truth (Inform 7 source)
├── $NAME.ulx              ← Compiled Glulx binary (build output)
├── web/
│   ├── play.html          ← Browser-playable game (Parchment player)
│   └── lib/parchment/     ← Parchment JS libraries + $NAME.ulx.js
└── tests/
    ├── project.conf       ← Test configuration
    ├── run-tests.sh       ← RegTest runner (wrapper)
    ├── run-walkthrough.sh ← Walkthrough runner (wrapper)
    ├── find-seeds.sh      ← Seed discovery (wrapper)
    ├── seeds.conf         ← Golden seeds
    ├── $NAME.regtest      ← Regression tests
    └── inform7/
        ├── walkthrough.txt        ← Walkthrough commands
        └── walkthrough_output.txt ← Generated transcript
\`\`\`

## Shared Resources

- **Inform 7 hub**: \`C:\\code\\ifhub\\CLAUDE.md\`
- **Syntax reference**: \`C:\\code\\ifhub\\reference\\syntax-guide.md\`
- **Text formatting**: \`C:\\code\\ifhub\\reference\\text-formatting.md\`
- **Testing framework**: \`C:\\code\\ifhub\\tools\\testing\\\`
- **Web player setup**: \`C:\\code\\ifhub\\tools\\web\\\`

## Build & Deploy

\`\`\`bash
# Compile + set up web player
bash /c/code/ifhub/tools/compile.sh $NAME

# Publish to GitHub Pages (first time creates repo)
bash /c/code/ifhub/tools/publish.sh $NAME
\`\`\`

## Testing

\`\`\`bash
wsl -e bash tests/run-walkthrough.sh --no-seed --no-save
wsl -e bash tests/run-tests.sh
wsl -e bash tests/find-seeds.sh
\`\`\`

## Play Locally

\`\`\`bash
python -m http.server 8000 --directory web
# Then open http://localhost:8000/play.html
\`\`\`

## Key Rules

- \`story.ni\` is the single source of truth
- Do NOT create \`.inform/\` IDE bundles
- For Inform 7 syntax and conventions, see \`C:\\code\\ifhub\\CLAUDE.md\`
CLAUDE_EOF

echo ""
echo "Project created at: $PROJECT_DIR"
echo ""
echo "Next steps:"
echo "  1. Edit $PROJECT_DIR/story.ni"
echo "  2. Compile:  bash $I7_ROOT/tools/compile.sh $NAME"
echo "  3. Test:     cd $PROJECT_DIR && wsl -e bash tests/run-tests.sh"
echo "  4. Publish:  bash $I7_ROOT/tools/publish.sh $NAME"
