#!/usr/bin/env python3
"""Create a new Inform 7 project with build, test, and web infrastructure.

Usage:
    python tools/new_project.py "Game Title" game-name

Creates a complete project scaffold with story.ni, tests, CI, and CLAUDE.md.
"""

import argparse
import re
import sys
import textwrap
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.paths import PROJECTS_DIR, I7_ROOT


def main():
    parser = argparse.ArgumentParser(description="Create a new Inform 7 project.")
    parser.add_argument("title", help="Game title (quoted)")
    parser.add_argument("name", help="Project directory name (lowercase)")
    args = parser.parse_args()

    title = args.title
    name = args.name
    project_dir = PROJECTS_DIR / name

    if project_dir.is_dir():
        print(f"ERROR: Directory already exists: {project_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Creating project: {title} ({name})")
    print(f"  Location: {project_dir}")
    print()

    # Directories
    (project_dir / "tests" / "inform7").mkdir(parents=True)
    (project_dir / ".github" / "workflows").mkdir(parents=True)

    year = datetime.now().year

    # story.ni
    (project_dir / "story.ni").write_text(textwrap.dedent(f"""\
        "{title}" by "Johnesco"

        The story headline is "An Interactive Fiction".
        The story genre is "Fantasy".
        The release number is 1.
        The story creation year is {year}.
        The story description is "An interactive fiction game."

        Use American dialect.
        Use scoring.
        The maximum score is 1.

        Part 1 - Configuration

        When play begins:
        \tnow the left hand status line is "[the player's surroundings]   Score: [score]/[turn count]";
        \tnow the right hand status line is "";
        \tsay "[bold type]{title}[roman type][line break]An Interactive Fiction by Johnesco[paragraph break]".

        Part 2 - The World

        The Starting Room is a room. "You are in an empty room. This is where your game begins."
    """), encoding="utf-8")

    # .gitignore
    (project_dir / ".gitignore").write_text(textwrap.dedent("""\
        # Assembled site output (generated by build_site.py / CI)
        _site/

        # Build output
        *.ulx
        *.i6
        *.materials/

        # Inform 7 IDE project wrappers
        *.inform/

        # Pipeline state (generated by pipeline.py)
        .pipeline-state

        # Claude Code local settings
        .claude/

        # Test output (generated)
        tests/inform7/walkthrough_output.txt

        # OS generated files
        $RECYCLE.BIN/
        [Dd]esktop.ini
        .DS_Store
        Thumbs.db
        *~
        .*.sw[op]

        # IDE
        .vscode/
        .idea/
    """), encoding="utf-8")

    # deploy-pages.yml
    (project_dir / ".github" / "workflows" / "deploy-pages.yml").write_text(textwrap.dedent("""\
        name: Deploy to GitHub Pages

        on:
          push:
            branches: [main]
          workflow_dispatch:

        permissions:
          contents: read
          pages: write
          id-token: write

        concurrency:
          group: pages
          cancel-in-progress: false

        jobs:
          deploy:
            environment:
              name: github-pages
              url: ${{ steps.deployment.outputs.page_url }}
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - uses: actions/configure-pages@v5
              - name: Assemble site
                run: |
                  mkdir -p _site
                  [ -d web ] && cp -r web/* _site/ || true
                  [ -d lib ] && cp -r lib _site/ || true
                  cp *.html _site/ 2>/dev/null || true
                  cp *.txt _site/ 2>/dev/null || true
                  cp *.ni _site/ 2>/dev/null || true
                  cp *.ink _site/ 2>/dev/null || true
                  cp *.json _site/ 2>/dev/null || true
                  cp *.bas _site/ 2>/dev/null || true
              - uses: actions/upload-pages-artifact@v3
                with:
                  path: _site
              - id: deployment
                uses: actions/deploy-pages@v4
    """), encoding="utf-8")

    # tests/project.conf (KV config, parsed by tools/lib/config.py)
    (project_dir / "tests" / "project.conf").write_text(textwrap.dedent(f"""\
        #!/bin/bash
        # {title} -- project-specific test configuration
        # Parsed by the testing framework (tools/testing/*.py)
        #
        # PROJECT_DIR is set by the framework before sourcing this file.

        # Project identity
        PROJECT_NAME="{title}"

        # Primary engine (Inform 7 / Glulx)
        PRIMARY_ENGINE_NAME="glulxe"
        PRIMARY_ENGINE_PATH="$HOME/glulxe/glulxe"
        PRIMARY_ENGINE_SEED_FLAG="--rngseed"
        PRIMARY_GAME_PATH="$PROJECT_DIR/{name}.ulx"
        PRIMARY_WALKTHROUGH="$PROJECT_DIR/tests/inform7/walkthrough.txt"
        PRIMARY_OUTPUT_FILE="$PROJECT_DIR/tests/inform7/walkthrough_output.txt"
        PRIMARY_SEEDS_KEY="glulxe"

        # Score extraction patterns (Inform 7 default output format)
        SCORE_REGEX='scored \\K[0-9]+'
        SCORE_FALLBACK_REGEX='[0-9]+(?= out of a possible [0-9]+)'
        MAX_SCORE_REGEX='possible \\K[0-9]+'
        PASS_THRESHOLD=1
        DEFAULT_MAX_SCORE=1

        # Diagnostic patterns
        DEATH_PATTERNS='you have died'
        WON_PATTERNS='You have won'

        # RegTest config
        REGTEST_FILE="$PROJECT_DIR/tests/{name}.regtest"
        REGTEST_ENGINE="$HOME/glulxe/glulxe"
        REGTEST_GAME="$PROJECT_DIR/{name}.ulx"

        # Pipeline config (used by tools/pipeline.py, ignored by testing framework)
        PIPELINE_SOUND=false
        PIPELINE_HUB_ID="{name}"
        PIPELINE_TESTS="walkthrough,regtest"
    """), encoding="utf-8")

    # seeds.conf
    (project_dir / "tests" / "seeds.conf").write_text(textwrap.dedent("""\
        # Golden seeds for deterministic walkthrough testing
        # Format: engine:seed:binary_hash:date
        # Re-discover with: python tools/testing/find_seeds.py --config tests/project.conf
        #
        # glulxe:TBD:TBD:TBD
    """), encoding="utf-8")

    # Starter regtest
    (project_dir / "tests" / f"{name}.regtest").write_text(textwrap.dedent(f"""\
        ** game: ../{name}.ulx
        ** interpreter: /home/johnesco/glulxe/glulxe -q

        * smoke
        > look
        Starting Room
    """), encoding="utf-8")

    # Starter walkthrough
    (project_dir / "tests" / "inform7" / "walkthrough.txt").write_text("look\n", encoding="utf-8")

    # CLAUDE.md
    (project_dir / "CLAUDE.md").write_text(textwrap.dedent(f"""\
        # {title} -- An Inform 7 Game

        ## Project Structure

        ```
        C:\\code\\ifhub\\projects\\{name}\\
        ├── CLAUDE.md              <- You are here
        ├── story.ni               <- Source of truth (Inform 7 source)
        ├── {name}.ulx              <- Compiled Glulx binary (build output)
        ├── play.html              <- Browser-playable game (Parchment player)
        ├── lib/parchment/         <- Parchment JS libraries + {name}.ulx.js
        ├── .github/workflows/     <- GitHub Actions workflow for Pages deployment
        └── tests/
            ├── project.conf       <- Test configuration
            ├── seeds.conf         <- Golden seeds
            ├── {name}.regtest      <- Regression tests
            └── inform7/
                ├── walkthrough.txt        <- Walkthrough commands
                └── walkthrough_output.txt <- Generated transcript
        ```

        ## Shared Resources

        - **Inform 7 hub**: `C:\\code\\ifhub\\CLAUDE.md`
        - **Syntax reference**: `C:\\code\\ifhub\\reference\\syntax-guide.md`
        - **Text formatting**: `C:\\code\\ifhub\\reference\\text-formatting.md`
        - **Testing framework**: `C:\\code\\ifhub\\tools\\testing\\`
        - **Web player setup**: `C:\\code\\ifhub\\tools\\web\\`

        ## Build & Deploy

        ```bash
        # Compile + set up web player
        python /c/code/ifhub/tools/compile.py {name}

        # Publish to GitHub Pages (first time creates repo)
        python /c/code/ifhub/tools/publish.py {name}
        ```

        ## Testing

        ```bash
        python /c/code/ifhub/tools/testing/run_walkthrough.py --config tests/project.conf --no-seed --no-save
        python /c/code/ifhub/tools/testing/run_tests.py --config tests/project.conf
        python /c/code/ifhub/tools/testing/find_seeds.py --config tests/project.conf
        ```

        ## Play Locally

        ```bash
        python -m http.server 8000
        # Then open http://localhost:8000/play.html
        ```

        ## Key Rules

        - `story.ni` is the single source of truth
        - Do NOT create `.inform/` IDE bundles
        - For Inform 7 syntax and conventions, see `C:\\code\\ifhub\\CLAUDE.md`
    """), encoding="utf-8")

    print()
    print(f"Project created at: {project_dir}")
    print()
    print("Next steps:")
    print(f"  1. Edit {project_dir / 'story.ni'}")
    print(f"  2. Compile:  python {I7_ROOT / 'tools' / 'compile.py'} {name}")
    print(f"  3. Test:     cd {project_dir} && python tests/run-tests.py")
    print(f"  4. Publish:  python {I7_ROOT / 'tools' / 'publish.py'} {name}")


if __name__ == "__main__":
    main()
